set -x CHICKEN_INSTALL_PREFIX $XDG_DATA_HOME/chicken
set -x CHICKEN_INSTALL_REPOSITORY $CHICKEN_INSTALL_PREFIX/lib
set -x CHICKEN_REPOSITORY_PATH /usr/lib64/chicken/11/ $CHICKEN_INSTALL_REPOSITORY

fish_add_path $CHICKEN_INSTALL_PREFIX/bin
