[colors.bright]
black = "#C6C3C3"
blue = "#1D5573"
cyan = "#2B747C"
green = "#060E0C"
magenta = "#7B3B70"
red = "#94253E"
white = "#5C5C5C"
yellow = "#803D1C"

[colors.cursor]
cursor = "#CFCFCF"
text = "#1A1A19"

[colors.normal]
black = "#EEEEEE"
blue = "#286486"
cyan = "#3B8992"
green = "#116432"
magenta = "#88507D"
red = "#A8334C"
white = "#353535"
yellow = "#944927"

[colors.primary]
background = "#FDFDFC"
foreground = "#222222"
