output $laptop scale 1.0

output $laptop  position 0 1080
output $monitor position 0 0

workspace 1 output $laptop
workspace 6 output $monitor

output $laptop bg $XDG_STATE_HOME/wallpaper fill

bindswitch --reload lid:on output $laptop disable
bindswitch --reload lid:off output $laptop enable
