theme = "rasmus-bright"

[editor]
auto-format = true
color-modes = true
shell = ["fish", "-c"]
gutters = []
scrolloff = 1
text-width = 100
idle-timeout = 50
completion-trigger-len = 1
insert-final-newline = true

[editor.statusline]
left = ["mode", "file-base-name", "file-modification-indicator"]
right = ["position", "file-type"]

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
G = "goto_file_end"

[keys.select]
G = "goto_file_end"

[keys.insert]
C-p = "move_visual_line_up"
C-n = "move_visual_line_down"
C-f = "move_char_right"
C-b = "move_char_left"
C-a = "goto_line_start"
C-e = "goto_line_end_newline"

C-u = "kill_to_line_start"
C-k = "kill_to_line_end"

C-h = "delete_char_backward"
C-d = "delete_char_forward"

C-w = "delete_word_backward"
A-d = "delete_word_forward"

A-f = "move_next_word_end"
A-b = "move_prev_word_start"
